/**
*  Generated by tpp tool
*  File: ctci_comparator_sorting.cpp
*  Created: 11-01-2024 14:30:08
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


bool order(pair<string, int> p1, pair<string, int> p2) {
  if(p1.second == p2.second) return p1.first < p2.first;
  else return p1.second > p2.second;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    vector<pair<string, int>> V;
    for(int i = 0; i < n; i++) {
      string name;
      int score;

      cin>>name>>score;
      V.push_back(make_pair(name, score));
    }

    sort(V.begin(), V.end(), order);

    for(int i = 0; i < V.size(); i++) {
      cout<<V[i].first<<" "<<V[i].second<<endl;
    }

    return 0;
}

