/**
*  Generated by tpp tool
*  File: two_strings.cpp
*  Created: 11-01-2024 15:22:29
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int p;
    cin>>p;

    while(p--) {
      string s1, s2;
      cin>>s1>>s2;

      unordered_map<char, bool> M;
      bool found = 0;

      for(int i = 0; i < s1.size(); i++) M[s1[i]] = 1;
      for(int i = 0; i < s2.size(); i++) {
        if(M[s2[i]]) {
          found = 1;
          break;
        }
      }

      if(found) cout<<"YES"<<endl;
      else cout<<"NO"<<endl;
    }

    return 0;
}

