/**
*  Generated by tpp tool
*  File: BILLRD.cpp
*  Created: 07-01-2021 22:45:52
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);
    
    int T;
    cin>>T;

    while(T--) {
    	int N, K, x, y;
    	cin>>N>>K>>x>>y;

    	if(x - y == 0) cout<<N<<" "<<N<<endl;
    	else {
    		vector< pair<int,int>> A(4);
    		if(x - y < 0) {
				A[0].first = x + N - y; A[0].second = N;
    			A[1].first = N; A[1].second = A[0].first;
    			A[2].first = N - A[1].second; A[2].second = 0;
    			A[3].first = 0; A[3].second = A[2].first;
    		}
			else {
    			A[0].first = N; A[0].second = y + N - x;
    			A[1].first = A[0].second; A[1].second = N;
    			A[2].first = 0; A[2].second = N - A[1].first;
    			A[3].first = A[2].second; A[3].second = 0;
			}

    		int ind = (K - 1) % 4;
    		cout<<A[ind].first<<" "<<A[ind].second<<endl;
    	}
    }


    return 0;
}
