/**
*  Generated by tpp tool
*  File: CHEFEZQ.cpp
*  Created: 02-10-2020 15:40:53
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;

    for(int cases = 0; cases < T; cases++) {
    	long long n, k;
    	cin>>n>>k;

    	vector<int> V(n);
    	for(int i = 0; i < n; i++) cin>>V[i];
    	long long  ans = 0;
    	long long  remain = 0;
    	for(int i = 0; i < n; i++) {
   			long long Q = V[i];
    		Q += remain;
    		if(Q < k) { ans++; break;}
    		else {
    			if(i == n - 1) ans += (Q/k) + 1;
    			else {
    				remain = Q - k;
    				ans++;
    			}
    		}
    	}
    	cout<<ans<<endl;
    }

    return 0;
}
