/**
*  Generated by tpp tool
*  File: DECODEIT.cpp
*  Created: 02-01-2021 13:29:25
**/

#include <bits/stdc++.h>
using namespace std;



int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    map<string, char> M;
    for(int i = 0; i < 16; i++) {
    	string code = std::bitset<4>(i).to_string();
    	M[code] = (char)('a' + i);
    }

    int T;
    cin>>T;
    while(T--) {
    	int N;
    	string S, code, ans;
    	cin>>N>>S;

    	ans = "";
    	code = "";
    	for(int i = 0; i < N; i++){
    		if(i > 0 && i % 4 == 0) {
    			ans += M[code];
    			code = "";
    		}
    		code += S[i];
    	}
    	ans += M[code];

    	cout<<ans<<endl;
    }

    return 0;
}
