/**
*  Generated by tpp tool
*  File: DIVTHREE.cpp
*  Created: 02-01-2021 13:15:17
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;

    while(T--) {
    	long long int N, K, D, A, sum, ans;
    	cin>>N>>K>>D;

    	sum = 0;
    	for(int i = 0; i < N; i++) {
    		cin>>A;
    		sum += A;
    	}

    	ans = min(D, sum/K);
    	cout<<ans<<endl;
    }

    return 0;
}
