/**
*  Generated by tpp tool
*  File: FAIRELCT.cpp
*  Created: 02-01-2021 14:23:00
**/

#include <bits/stdc++.h>
using namespace std;


bool order(int a, int b) {
	return a > b;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;
    while(T--){
    	int N, M;
    	cin>>N>>M;

		priority_queue<int, vector<int>, greater<int>> Min;
    	priority_queue<int> Max;
    	long long int sumA = 0;
    	long long int sumB = 0;

    	for(int i = 0; i < N; i++) {
    		int a;
    		cin>>a;
    		Min.push(a);
    		sumA += a;
    	}

    	for(int i = 0; i < M; i++) {
    		int b;
    		cin>>b;
    		Max.push(b);
    		sumB += b;
    	}	

    	int ans = 0;
    	while(1) {
    		if(sumA > sumB) break;

    		int a = Min.top();
    		int b = Max.top();
    		if(b <= a) {
    			ans = -1;
    			break;
    		}

    		Min.pop();
    		Max.pop();

    		sumA = sumA - a + b;
    		sumB = sumB - b + a;
    		ans++;

    		Min.push(b);
    		Max.push(a);
    	}

    	cout<<ans<<endl;
    }

    return 0;
}
