/**
*  Generated by tpp tool
*  File: HDIVISR.cpp
*  Created: 05-02-2021 22:18:01
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    cin>>N;

    int ans;
    for(ans = 10; ans >= 1; ans--) {
        if(N % ans == 0) break;
    }

    cout<<ans<<endl;

    return 0;
}
