/**
*  Generated by tpp tool
*  File: INTRVS.cpp
*  Created: 30-01-2021 13:25:14
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;

    while(T--) {
        int N, K;
        cin>>N>>K;

        int solved = 0;
        int bot = 0;
        bool slow = false;

        for(int i = 0; i < N; i++) {
            int a;
            cin>>a;
            if(a != -1){
                solved++;
                if(a <= K) {
                    if(a >= 0 && a <= 1) bot++;
                } else {
                    slow = true;
                }
            }
        }

        if(solved < ceil(N/2.0)) cout<<"Rejected"<<endl;
        else {
            if(slow) cout<<"Too Slow"<<endl;
            else {
                if(bot == N) cout<<"Bot"<<endl;
                else cout<<"Accepted"<<endl;
            }
        }
    }

    return 0;
}
