/**
*  Generated by tpp tool
*  File: MAXFUN.cpp
*  Created: 05-02-2021 22:29:03
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;

    while(T--){
        int N;
        cin>>N;

        vector<long long int> V(N);
        for(int i = 0; i < N; i++) cin>>V[i];
        sort(V.begin(), V.end());

        long long int ans = 2*abs(V[N-1] - V[0]);
        cout<<ans<<endl;
    }

    return 0;
}
