/**
*  Generated by tpp tool
*  File: MEET.cpp
*  Created: 06-02-2021 01:37:19
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int hoursToMinutes(int HH, int MM){
    return 60*HH + MM;
}

int hoursFromClockFormat(int HH, string time){
    if(time == "AM" && HH == 12) return  0;
    if(time == "PM" && HH < 12) return HH + 12;
    return HH;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    string input;
    char s;

    int T;
    cin>>T;
    getline(cin, input);

    while(T--) {
        getline(cin, input);

        int hh, mm, meetingTime;
        string time;
        stringstream in(input);
        in>>hh>>s>>mm>>time;

        hh = hoursFromClockFormat(hh, time);
        meetingTime = hoursToMinutes(hh, mm);

        int N;
        cin>>N;
        getline(cin, input);

        for(int i = 0; i < N; i++) {
            getline(cin, input);

            int hh1, mm1, startTime, hh2, mm2, endTime;
            string time1, time2;
            stringstream in(input);
            in>>hh1>>s>>mm1>>time1>>hh2>>s>>mm2>>time2;
            
            hh1 = hoursFromClockFormat(hh1, time1);
            hh2 = hoursFromClockFormat(hh2, time2);
            startTime = hoursToMinutes(hh1, mm1);
            endTime = hoursToMinutes(hh2, mm2);

            if(meetingTime >= startTime && meetingTime <= endTime) cout<<"1";
            else cout<<"0";
        }
        
        cout<<endl;
    }

    return 0;
}
