/**
*  Generated by tpp tool
*  File: POSAND.cpp
*  Created: 02-10-2020 19:06:05
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;

    for(int cases = 0; cases < T; cases++) {
    	int N;
    	cin>>N;

    	if(N == 1) {
    		cout<<1<<endl;
    		continue;
    	}
		
    	if((N & (N - 1)) == 0) {
    		cout<<-1<<endl;
    		continue;
    	}

    	vector<int> v;
    	queue<int> q;

    	v.push_back(2);
    	q.push(1);
    	int current = 2;

    	while(v.size() < N) {
    		q.push(++current); 

    		int a = v[v.size() - 1];
    		int b = q.front();
    		q.pop();

    		if((a & b) != 0) v.push_back(b);
    		else {
    			v.push_back(q.front());
    			q.pop();
    			q.push(b);
    		}
    	}

    	for(int i = 0; i < v.size(); i++) {
    		if(i > 0) cout<<" ";
    		cout<<v[i];
    	}
    	cout<<endl;
    }

    return 0;
}
