/**
*  Generated by tpp tool
*  File: SUMPOS.cpp
*  Created: 30-01-2021 12:49:19
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int T;
    cin>>T;

    while(T--) {
        int x, y, z;
        cin>>x>>y>>z;

        int tmp1 = x + y;
        int tmp2 = y + z;
        int tmp3 = x + z;

        if (x == tmp2 || y == tmp3 || z == tmp1) cout<<"YES"<<endl;
        else cout<<"NO"<<endl;
    }

    return 0;
}
