/**
*  Generated by tpp tool
*  File: WATMELON.cpp
*  Created: 29-09-2020 20:04:00
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
  // do not remove this code if you use cin or cout
  ios::sync_with_stdio(false);
  cin.tie(0);

  int T;
  cin>>T;

  for(int cases = 0; cases < T; cases++) {
  	int N;
  	cin>>N;

  	int num;
  	int sum = 0;
  	for(int i = 0; i < N; i++) {
  		cin>>num;
  		sum += num;
  	}
  	if(sum >= 0) cout<<"YES"<<endl;
  	else cout<<"NO"<<endl;
  }

  return 0;
}
