/**
*  Generated by tpp tool
*  File: dp_b_rec.cpp
*  Created: 26-02-2024 20:47:39
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


const int INF = 1e9+7;
const int MAX = 1e5+5;

int n, k;
int h[MAX];
int dp[MAX];

int solve(int pos) {
  if(pos > n) return INF;
  if(pos == n) return 0;
  if(dp[pos] != -1) return dp[pos];

  dp[pos] = INF;

  for(int i = 1; i <= k; i++) {
    if(pos + i <= n) {
      int costk = abs(h[pos + i] - h[pos]);
      dp[pos] = min(dp[pos], costk + solve(pos + i));
    }
  }

  return dp[pos];
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    memset(dp, -1, sizeof(dp));

    cin>>n>>k;

    for(int i = 1; i <= n; i++) cin>>h[i];

    cout<<solve(1)<<endl;

    return 0;
}
