/**
*  Generated by tpp tool
*  File: islands3.cpp
*  Created: 31-12-2023 18:12:56
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define LAND 'L'
#define CLOUD 'C'
#define WATER 'W'
#define MOV 4

int R, C;
vector<string> graph;
vector<vector<bool>> visited;

int dr[] = {0, 1, 0, -1};
int dc[] = {1, 0, -1, 0};

bool isValid(int r, int c) {
  return r >= 0 && r < R && c >= 0 && c < C;
}

void dfs(int r, int c) {
  visited[r][c] = 1;

  for(int k = 0; k < MOV; k++) {
    int nr = r + dr[k];
    int nc = c + dc[k];

    if(isValid(nr, nc) && !visited[nr][nc] && (graph[nr][nc] == LAND || graph[nr][nc] == CLOUD)) {
      dfs(nr, nc);
    }
  }
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    cin>>R>>C;

    graph = vector<string>(R);
    visited = vector<vector<bool>> (R, vector<bool>(C, 0));

    for(int i = 0; i < R; i++) cin>>graph[i];

    int ans = 0;
    for(int i = 0; i < R; i++) {
      for(int j = 0; j < C; j++) {
        if(!visited[i][j] && graph[i][j] == LAND) {
          dfs(i, j);
          ans++;
        }
      }
    }

    cout<<ans<<endl;

    return 0;
}

