/**
*  Generated by tpp tool
*  File: greedilyincreasing.cpp
*  Created: 06-10-2020 18:51:18
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    cin>>N;

    vector<int> A(N);
    for(int i = 0; i < N; i++) cin>>A[i];

    vector<int> ans;
	ans.push_back(A[0]);
	for(int i = 0; i < N; i++) {
		if(A[i] > ans[ans.size() - 1]) ans.push_back(A[i]);
	}

	cout<<ans.size()<<endl;
	for(int i = 0; i < ans.size(); i++) {
		if(i > 0) cout<<" ";
		cout<<ans[i];
	}
	cout<<endl;

    return 0;
}
