/**
*  Generated by tpp tool
*  File: mali.cpp
*  Created: 06-10-2020 20:56:16
**/

#include <bits/stdc++.h>
#define MAX 105
using namespace std;


int solve(vector<int> A, vector<int> B) {
    int i = 0;
    int j = 100;
    int ans = 0;
    bool flag = 0;
    while(1) {
        while(A[i] == 0) {
            i++;
            if(i > 100) {
                flag = 1;
                break;
            }
        }

        while(B[j] == 0) {
            j--;
            if(j < 0) {
                flag = 1;
                break;
            }
        }

        if(flag) break;

        ans = max(ans, i + j);

        int minOverlap = min(A[i], B[j]);
        A[i] = A[i] - minOverlap;
        B[j] = B[j] - minOverlap;
    }

    return ans;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);
	
	int N;
    cin>>N;

    vector<int> A(MAX, 0), B(MAX, 0);
    for(int k = 0; k < N; k++) {
        int a, b;
        cin>>a>>b;
        A[a]++;
        B[b]++;

        cout<<solve(A, B)<<endl;
    }

    return 0;
}
