/**
*  Generated by tpp tool
*  File: pivot.cpp
*  Created: 06-10-2020 19:14:43
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    vector<int> V(n);
    for(int i = 0; i < n; i++) cin>>V[i];

    vector<int> L(n), R(n);
	L[0] = V[0];
	R[n - 1] = V[n - 1];
	for(int i = 1; i < n; i++) {
		L[i] = max(V[i], L[i - 1]);
		R[n - 1 - i] = min(V[n - 1 - i], R[n - i]);
	}

	int cont = 0;
	for(int i = 0; i < n; i++) {
		bool left = (i == 0)? 1 : V[i] >= L[i - 1];
		bool right = (i == n - 1)? 1: V[i] < R[i + 1];
		if(left && right) cont++;
	}

	cout<<cont<<endl;

    return 0;
}
