/**
*  Generated by tpp tool
*  File: 1160A_Vasya_And_Coins.cpp
*  Created: 05-04-2022 15:03:14
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);
    
    int t;
    cin>>t;
    
    while(t--) {
      long long a, b, ans;
      cin>>a>>b;
      
      if(a == 0) ans = 1;
      else ans = a + 2*b + 1;
      
      cout<<ans<<endl;
    }

    return 0;
}

