/**
*  Generated by tpp tool
*  File: 1328A_Divisibility_Problem.cpp
*  Created: 16-04-2024 17:50:22
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int a, b;
      cin>>a>>b;

      int ans = 0;
      if(a % b != 0) ans = b - (a % b);

      cout<<ans<<endl;
    }

    return 0;
}

