/**
*  Generated by tpp tool
*  File: 136A_Presents.cpp
*  Created: 29-03-2024 18:10:32
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    vector<int> P(n + 1), G(n + 1);
    for(int i = 1; i <= n; i++) {
      cin>>P[i];

      G[P[i]] = i;
    }

    for(int i = 1; i <= n; i++) {
      if(i > 1) cout<<" ";
      cout<<G[i];
    }
    cout<<endl;

    return 0;
}

