/**
*  Generated by tpp tool
*  File: 1408A.cpp
*  Created: 30-09-2020 16:29:27
**/

#include <bits/stdc++.h>
using namespace std;


int main() {
	// do not remove this code if you use cin or cout
	ios::sync_with_stdio(false);
	cin.tie(0);

	int t;
	cin>>t;
	for(int cases = 0; cases < t; cases++) {
		int n;
		cin>>n;

		vector<int> A(n), B(n), C(n);
		for(int i = 0; i < n; i++) cin>>A[i];
		for(int i = 0; i < n; i++) cin>>B[i];
		for(int i = 0; i < n; i++) cin>>C[i];

  		vector<int> ans(n, 0);
  		for(int i = 0; i < n; i++) {
  			if(i == 0) {
  				ans[i] = A[i];
  				continue;
  			}

  			if(i == n - 1) {
	  			if(ans[i - 1] != A[i] && ans[0] != A[i]) {ans[i] = A[i]; continue;}
	  			if(ans[i - 1] != B[i] && ans[0] != B[i]) {ans[i] = B[i]; continue;}
	  			if(ans[i - 1] != C[i] && ans[0] != C[i]) {ans[i] = C[i]; continue;}
  				continue;
  			}

  			if(ans[i - 1] != A[i]) {ans[i] = A[i]; continue;}
  			if(ans[i - 1] != B[i]) {ans[i] = B[i]; continue;}
  			if(ans[i - 1] != C[i]) {ans[i] = C[i]; continue;}
  		}

  		for(int i = 0; i < ans.size(); i++) {
  			if(i > 0) cout<<" ";
  			cout<<ans[i];
  		}
  		cout<<endl;
  }

  return 0;
}
