/**
*  Generated by tpp tool
*  File: 1420B_Rock_And_Lever.cpp
*  Created: 11-04-2024 15:12:30
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;



int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      map<int, long long int> M;
      for(int i = 0; i < n; i++) {
        int a;
        cin>>a;

        M[log2(a)]++;
      }

      long long int ans = 0;
      for(pair<int,long long int> p : M) {
        ans += (p.second)*(p.second - 1)/2;
      }

      cout<<ans<<endl;

    }

    return 0;
}

