/**
*  Generated by tpp tool
*  File: 158A_Next_Round.cpp
*  Created: 29-03-2024 01:16:37
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n, k;
    cin>>n>>k;

    vector<int> V(n);
    for(int i = 0; i < n; i++) cin>>V[i];
   
    int cont = 0;
    for(int i = 0; i < n; i++) {
      if(i < k && V[i] != 0) {
        cont++;
        continue;
      }
      
      if(V[i] == V[k - 1] && V[i] != 0) cont++;
    }

    cout<<cont<<endl;

    return 0;
}

