/**
*  Generated by tpp tool
*  File: 160A_Twins.cpp
*  Created: 16-04-2024 15:36:39
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


bool order(int a, int b) {
  return a > b;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    vector<int> V(n);
    int sum = 0;

    for(int i = 0; i < n; i++) {
      cin>>V[i];
      sum += V[i];
    }

    sort(V.begin(), V.end(), order);

    int cont = 0;
    int acum = 0;
    for(int i = 0; i < V.size(); i++) {
      if(acum  > sum) continue;

      acum += V[i];
      sum -= V[i];
      cont++;
    }

    cout<<cont<<endl;

    return 0;
}

