/**
*  Generated by tpp tool
*  File: 1808B_Playing_In_A_Casino.cpp
*  Created: 13-02-2024 23:07:39
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


bool order(int a, int b) {
  return a > b;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n, m;
      cin>>n>>m;

      vector<vector<long long int>> V(m, vector<long long int>(n));
      for(int i = 0; i < n; i++) {
        for(int j = 0; j < m; j++) cin>>V[j][i];
      }

      long long int total = 0;
      for(int i = 0; i < m; i++) {
        sort(V[i].begin(), V[i].end(), order);


        for(int j = 0; j < n; j++) {
          total += V[i][j]*(n - j - 1);
          total -= V[i][j]*(j);
        }
      }

      cout<<total<<endl;
    }

    return 0;
}

