/**
*  Generated by tpp tool
*  File: 1811A_Insert_Digit.cpp
*  Created: 09-04-2024 11:52:53
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      char d;
      string number;

      cin>>n>>d;
      cin>>number;

      string ans = "";
      bool found = 0;
      for(int i = 0; i < n; i++) {
        if(!found && d > number[i]) {
          ans += d;
          found = 1;
        }

        ans += number[i];
      }

      if(!found) ans += d;

      cout<<ans<<endl;
    }

    return 0;
}

