/**
*  Generated by tpp tool
*  File: E.cpp
*  Created: 28-12-2023 12:30:52
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      map<long long int, bool> M;
      long long int num, acum;
      string ans = "NO";

      acum = 0;
      M[0] = 1;
      for(int i = 0; i < n; i++) {
        cin>>num;
        if(i % 2 != 0) acum += num;
        else acum -= num;

        if(M[acum]) ans = "YES";

        M[acum] = 1;
      }

      cout<<ans<<endl;
    }

    return 0;
}

