/**
*  Generated by tpp tool
*  File: 1921A_Square.cpp
*  Created: 15-01-2024 11:39:34
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int cases;
    cin>>cases;

    while(cases--) {
      vector<pair<int,int>> V;

      for(int i = 0; i< 4; i++) {
        int x, y;
        cin>>x>>y;
        V.push_back(make_pair(x,y));
      }

      sort(V.begin(), V.end());
      int area = abs(V[0].second - V[1].second) * abs(V[1].first - V[2].first);
      cout<<area<<endl;
    }

    return 0;
}

