/**
*  Generated by tpp tool
*  File: 1927C_Choose_The_Different_Ones.cpp
*  Created: 06-02-2024 17:10:52
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define SET 3

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int cases;
    cin>>cases;

    while(cases--) {
      int n, m, k, num;
      cin>>n>>m>>k;

      unordered_set<int> first, second;
      
      for(int i = 0; i < n; i++) {
        cin>>num;
        first.insert(num);
      }

      for(int i = 0; i < m; i++) {
        cin>>num;
        second.insert(num);
      }

      // Compute
      vector<int> V(k, -1);

      for(int e : first) {
        if(e > 0 && e <= k) V[e - 1] = 0;
      }

      for(int e : second) {
        if(e > 0 && e <= k) {
          V[e - 1] = (V[e - 1] != -1)? 2 : 1;
        }
      }

      vector<int> cont(SET);
      bool isComplete = 1;
      for(int i = 0; i < k; i++) {
        if(V[i] == -1) isComplete = 0;
        else cont[V[i]]++;
      }

      if(isComplete) {
        int missing1 = k/2 - cont[0];
        int missing2 = k/2 - cont[1];

        if(missing1 >= 0 && missing2 >=0 && missing1 + missing2 == cont[2]) cout<<"YES"<<endl;
        else cout<<"NO"<<endl;
      } else cout<<"NO"<<endl;
    }

    return 0;
}

