/**
*  Generated by tpp tool
*  File: 1931B_Make_Equal.cpp
*  Created: 22-02-2024 16:46:56
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int cases;
    cin>>cases;

    while(cases--) {
      int n;
      cin>>n;

      vector<int> V(n);
      int sum = 0;
      for(int i = 0; i < n; i++) {
        cin>>V[i];
        sum += V[i];
      }

      int quantity = sum/n;
      
      bool isPossible = 1;
      int water = 0;
      for(int i = 0; i < n; i++) {
        if(V[i] + water >= quantity) {
          water = (V[i] + water) -  quantity;
        } else isPossible = 0;
      }

      if(isPossible) cout<<"YES"<<endl;
      else cout<<"NO"<<endl;
    }

    return 0;
}

