/**
*  Generated by tpp tool
*  File: 1931A_Recovering_A_Small_String.cpp
*  Created: 22-02-2024 16:30:42
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define LEN 3
#define MAX 25

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int cases;
    cin>>cases;

    while(cases--) {
      int n;
      cin>>n;

      vector<int> V(LEN, 0);
      n = n - LEN;

      for(int i = LEN - 1; i >= 0; i--) {
        if(n > 0) {
          V[i] = min(MAX, V[i] + n);
          n = n - min(MAX, V[i] + n);
        }
      }

      for(int i = 0; i < LEN; i++) cout<<(char)('a' + V[i]);
      cout<<endl;
    }

    return 0;
}

