/**
*  Generated by tpp tool
*  File: 1933D_Continual_Mods.cpp
*  Created: 28-02-2024 11:21:57
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int cases;
    cin>>cases;

    while(cases--) {
      int n;
      cin>>n;

      vector<int> V(n);
      for(int i = 0; i < n; i++) cin>>V[i];

      sort(V.begin(), V.end());

      string ans = "NO";

      if(V[0] != V[1]) ans = "YES";
      else {
        for(int i = 1; i < n; i++) {
          if(V[i] % V[0] != 0) {
            ans = "YES";
            break;
          }
        }
      }

      cout<<ans<<endl;
    }

    return 0;
}

