/**
*  Generated by tpp tool
*  File: 1933B_Fast_Three_Task.cpp
*  Created: 27-02-2024 22:33:27
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int cases;
    cin>>cases;

    while(cases--) {
      int n;
      cin>>n;

      map<int, int> M;
      int sum = 0;

      for(int i = 0; i < n; i++) {
        int num;
        cin>>num;

        sum += (num % 3);
        M[num % 3]++;
      }

      int ans = (3 - (sum % 3)) % 3;

      if(ans == 2 && M.count(1)) cout<<1<<endl;
      else cout<<ans<<endl;

    }

    return 0;
}

