/**
*  Generated by tpp tool
*  File: 1950B_Upscaling.cpp
*  Created: 28-03-2024 11:49:59
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      string black = "##";
      string white = "..";

      bool isInitBlack = 1;

      for(int i = 0; i < n; i++) {

        for(int k = 0; k < 2; k++) {
          bool isBlack = isInitBlack;
          
          for(int j = 0; j < n; j++) {
            if(isBlack) cout<<black;
            else cout<<white;

            isBlack = !isBlack;
          }
          cout<<endl;
        }

        isInitBlack = !isInitBlack;
      }
    }

    return 0;
}

