/**
*  Generated by tpp tool
*  File: 1950C_Clock_Conversion.cpp
*  Created: 28-03-2024 11:58:57
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;



void print(int h, int m, string z) {
  if(h < 10) cout<<"0"<<h<<":";
  else cout<<h<<":";

  if(m < 10) cout<<"0"<<m<<" "<<z<<endl;
  else cout<<m<<" "<<z<<endl;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      string s;
      cin>>s;

      int hours = stoi(s.substr(0,2)); 
      int minutes = stoi(s.substr(3,2));

      if(hours == 12) {
        print(hours, minutes, "PM");
        continue;
      }
      if(hours == 0) {
        print(12, minutes, "AM");
        continue;
      }
      if(hours < 12) {
        print(hours, minutes, "AM");
        continue;
      }
      print(hours - 12, minutes, "PM");
    }

    return 0;
}

