/**
*  Generated by tpp tool
*  File: 1950F_0_1_2_Tree.cpp
*  Created: 28-03-2024 19:47:57
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int a, b, c;
      cin>>a>>b>>c;

      if(a != c - 1) {
        cout<<-1<<endl;
        continue;
      }

      int height = ceil((float)b/c);
      int freeLeafs = c - b % c;

      if(freeLeafs != c) a = a - freeLeafs/2;
      
      height += ceil(log2(a + 1));

      cout<<height<<endl;
    }

    return 0;
}

