/**
*  Generated by tpp tool
*  File: 1954A_Painting_The_Ribbon.cpp
*  Created: 14-04-2024 17:14:03
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n, m, k;
      cin>>n>>m>>k;

      int maxPartWithSameColor = ceil((double)n/m);
      if(k >= n - maxPartWithSameColor) cout<<"NO"<<endl;
      else cout<<"YES"<<endl;

    }

    return 0;
}

