/**
*  Generated by tpp tool
*  File: 1954C_Long_Multiplication.cpp
*  Created: 14-04-2024 18:07:17
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      string number1, number2;
      cin>>number1>>number2;

      int ind = 0;
      while(ind < number1.size()) {
        if(number1[ind] != number2[ind]) {
          if(number1[ind] < number2[ind]) swap(number1, number2);
          break;
        }
        
        ind++;
      }

      for(int i = ind + 1; i < number1.size(); i++) {
        if(number1[i] > number2[i]) swap(number1[i], number2[i]);
      }

      cout<<number1<<endl;
      cout<<number2<<endl;
    }

    return 0;
}

