
/**
*  Generated by tpp tool
*  File: 1955A_Yogurt_Sale.cpp
*  Created: 08-04-2024 11:38:03
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n, a, b;
      cin>>n>>a>>b;

      int one = a*n;
      int two = b*(n/2) + a*(n%2);

      int ans = min(one, two);
      cout<<ans<<endl;
    }

    return 0;
}

