/**
*  Generated by tpp tool
*  File: 1956A_Nenes_Game.cpp
*  Created: 14-04-2024 11:49:04
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int k, q;
      cin>>k>>q;

      vector<int> a(k);
      for(int i = 0; i < k; i++) cin>>a[i];

      for(int i = 0; i < q; i++) {
        if(i > 0) cout<<" ";

        int n;
        cin>>n;

        if(n < a[0]) cout<<n;
        else cout<<a[0] - 1;
      }
      cout<<endl;
    }

    return 0;
}

