/**
*  Generated by tpp tool
*  File: 1956B_Nene_And_The_Card_Game.cpp
*  Created: 14-04-2024 12:02:16
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      map<int, int> M;

      int ans = 0;
      for(int i = 0; i < n; i++) {
        int a;
        cin>>a;

        M[a]++;
        if(M[a] == 2) ans++;
      }

      cout<<ans<<endl;
    }

    return 0;
}

