/**
*  Generated by tpp tool
*  File: 1956C_Nenes_Magical_Matrix.cpp
*  Created: 14-04-2024 12:18:15
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      int sum = 0;
      for(int i = 0; i < n; i++) sum += (i + 1)*(2*i + 1);

      cout<<sum<<" "<<2*n<<endl;

      for(int i = 0; i < n; i++) {
        cout<<1<<" "<<n - i;
        for(int j = 1; j <= n; j++) cout<<" "<<j;
        cout<<endl;

        cout<<2<<" "<<n - i;
        for(int j = 1; j <= n; j++) cout<<" "<<j;
        cout<<endl;
      }
    }

    return 0;
}

