/**
*  Generated by tpp tool
*  File: 1968C_Assembly_Via_Remainders.cpp
*  Created: 04-05-2024 21:12:15
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      vector<int> A(n), ans(n);
      int maximum = 0;
      for(int i = 1; i < n; i++) {
        cin>>A[i];
        maximum = max(maximum, A[i]);
      }

      for(int i = 0; i < n; i++) {
        if(i == 0) ans[i] = maximum + 1;
        else ans[i] = ans[i - 1] + A[i];
      }

      for(int i = 0; i < n; i++) {
        if(i > 0) cout<<" ";
        cout<<ans[i];
      }
      cout<<endl;

    }

    return 0;
}

