/**
*  Generated by tpp tool
*  File: 1969A_Two_Friends.cpp
*  Created: 29-04-2024 11:44:29
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


const int MIN = 100;

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      vector<int> V(n + 1);
      for(int i = 1; i <= n; i++) cin>>V[i];

      vector<bool> visited(n + 1, 0);
      int minimum = MIN;

      for(int i = 1; i <= n; i++) {
        int cont = 0;
        int ind = i;

        while(!visited[ind]) {
          visited[ind] = 1;
          ind = V[ind];
          cont++;
        }

        if(cont > 0) minimum = min(minimum, cont);
      }

      if(minimum > 2) cout<<3<<endl;
      else cout<<2<<endl;
    }

    return 0;
}

