/**
*  Generated by tpp tool
*  File: 1969A_Two_Friends.cpp
*  Created: 29-04-2024 11:44:29
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


const int MIN = 100;

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      vector<int> V(n + 1);
      for(int i = 1; i <= n; i++) cin>>V[i];

      int ans = 3;
      for(int i = 1; i <= n; i++) {
        if(i == V[V[i]]) {
          ans = 2;
          break;
        }
      }

      cout<<ans<<endl;
    }

    return 0;
}

