/**
*  Generated by tpp tool
*  File: 1969B_Shifts_And_Sorting.cpp
*  Created: 29-04-2024 12:43:24
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      string s;
      cin>>s;

      long long int cont = 0;
      long long int ans = 0;
      for(int i = 0; i < s.size(); i++) {
        if(s[i] == '1') cont++;
        else {
          if(cont > 0) ans += cont + 1;
        }
      }

      cout<<ans<<endl;
    }

    return 0;
}

