/**
*  Generated by tpp tool
*  File: 1971D_Binary_Cut.cpp
*  Created: 12-05-2024 04:21:23
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      string s;
      cin>>s;

      int cuts = 0;
      for(int i = 1; i < s.size(); i++) {
        if(s[i] != s[i - 1]) cuts++;
      }

      if(cuts == 0) cout<<1<<endl;
      else {
        if(cuts == 1) {
          if(s[0] == '0') cout<<1<<endl;
          else cout<<2<<endl;
        } else {
          if (cuts == 2) cout<<2<<endl;
          else cout<<cuts<<endl;
        }
      }
    }

    return 0;
}

