/**
*  Generated by tpp tool
*  File: 1971A_My_First_Sorting_Problem.cpp
*  Created: 12-05-2024 03:51:25
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int x, y;
      cin>>x>>y;
      cout<<min(x, y)<<" "<<max(x, y)<<endl;
    }

    return 0;
}

