/**
*  Generated by tpp tool
*  File: 1971B_Different_String.cpp
*  Created: 12-05-2024 03:54:20
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      string s;
      cin>>s;

      bool sameChar = 1;
      int x = -1;
      int y = -1;

      for(int i = 1; i < s.size(); i++) {
        if(s[i] != s[i - 1]) {
          sameChar = 0;
          x = i;
          y = i - 1;
          break;
        }
      }

      if(sameChar) cout<<"NO"<<endl;
      else {
        swap(s[x], s[y]);
        cout<<"YES"<<endl;
        cout<<s<<endl;
      }
    }

    return 0;
}

