/**
*  Generated by tpp tool
*  File: 1971C_Clock_And_Strings.cpp
*  Created: 12-05-2024 04:01:14
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int a, b, c, d;
      cin>>a>>b>>c>>d;

      int l = min(a, b);
      int r = max(a, b);

      int cont = 0;
      int index = l;
      while(index != r){
        if(index == 12) index = 0;
        if(index == c) cont++;
        if(index == d) cont++;
        index++;
      }

      if(cont == 2 || cont == 0) cout<<"NO"<<endl;
      else cout<<"YES"<<endl;
    }

    return 0;
}

