/**
*  Generated by tpp tool
*  File: 1972B_Coin_Games.cpp
*  Created: 30-04-2024 12:18:15
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      string s;
      cin>>s;

      int cont = 0;
      for(int i = 0; i < s.size(); i++) {
        if(s[i] == 'D') cont++;
      }

      if(s.size() % 2 == 0) {
        if(cont % 2 == 0) cout<<"NO"<<endl;
        else cout<<"YES"<<endl;
      } else {
        if(cont % 2 == 0) cout<<"YES"<<endl;
        else cout<<"NO"<<endl;
      }
    }

    return 0;
}

