/**
*  Generated by tpp tool
*  File: 1972A_Contest_Proposal.cpp
*  Created: 30-04-2024 11:40:54
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      vector<int> a(n), b(n);
      for(int i = 0; i < n; i++) cin>>a[i];
      for(int i = 0; i < n; i++) cin>>b[i];

      int ans = 0;
      int pa = 0;
      int pb = 0;

      while(pa < n && pb < n) {
        if(a[pa] <= b[pb]) {
          pa++;
          pb++;
          continue;
        }

        ans++;
        pb++;
      }

      cout<<ans<<endl;
    }

    return 0;
}

