/**
*  Generated by tpp tool
*  File: 1979A_Guess_The_Maximum.cpp
*  Created: 07-06-2024 11:38:54
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


const int INF = 1e9 + 5;

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      vector<int> V(n);
      int ans = INF;
      for(int i = 0; i < n; i++) {
        cin>>V[i];

        if(i > 0) ans = min(ans, max(V[i], V[i - 1]));
      }

      cout<<ans - 1<<endl;
    }

    return 0;
}

