/**
*  Generated by tpp tool
*  File: 1985C_Good_Prefixes.cpp
*  Created: 18-06-2024 09:19:58
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      vector<long long int> S(n), M(n);
      int ans = 0;

      for(int i = 0; i < n; i++) {
        cin>>S[i];
        M[i] = S[i];

        if(i > 0) {
          S[i] = S[i] + S[i - 1];
          M[i] = max(M[i], M[i - 1]);
        }
      }

      for(int i = 0; i < n; i++) {
        if(i == 0 && S[i] == 0) ans++;
        if(i > 0 && S[i] - M[i] == M[i]) ans++;
      }

      cout<<ans<<endl;
    }

    return 0;
}

