/**
*  Generated by tpp tool
*  File: 1985A_Creating_Words.cpp
*  Created: 17-06-2024 18:40:02
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      string a, b;
      cin>>a>>b;
      swap(a[0], b[0]);
      cout<<a<<" "<<b<<endl;
    }

    return 0;
}

