/**
*  Generated by tpp tool
*  File: 228A_Is_Your_Horseshoe_On_The_Other_Hoof.cpp
*  Created: 16-04-2024 17:37:57
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    map<int,int> M;
    int ans = 0;

    for(int i = 0; i < 4; i++) {
      int num;
      cin>>num;

      if(M[num] != 0) ans++;
      M[num]++;
    }

    cout<<ans<<endl;

    return 0;
}

