/**
*  Generated by tpp tool
*  File: 271A_Beautiful_Year.cpp
*  Created: 29-03-2024 02:10:09
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


bool haveDistictDigits(int n) {
  map<int, bool> M;
  bool areDistict = 1;

  while(n/10 > 0) {
    int digit = n % 10;
    if(M[digit]) {
      areDistict = 0;
      break;
    }

    M[digit] = 1;
    n = n/10;
  }

  if(M[n]) areDistict = 0;
  
  return areDistict;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int y;
    cin>>y;

    int ans = y + 1;
    while(!haveDistictDigits(ans)) ans++;

    cout<<ans<<endl;

    return 0;
}

