/**
*  Generated by tpp tool
*  File: 455A_Boredom.cpp
*  Created: 03-08-2024 20:34:48
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


const int MAX = 100005;

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    map<int, long long int> count;
    long long int maximum = 0;
    for(int i = 0; i < n; i++) {
      long long int a;
      cin>>a;

      count[a]++;
      maximum = max(maximum, a);
    }

    long long int dp[MAX];

    dp[0] = 0;
    dp[1] = count[1];
    for(long long int i = 2; i <= maximum; i++) {
      dp[i] = max(dp[i - 1], count[i] * i + dp[i - 2]);
    }

    cout<<dp[maximum]<<endl;

    return 0;
}

