/**
*  Generated by tpp tool
*  File: 520B_Two_Buttons.cpp
*  Created: 06-06-2024 13:42:12
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


const int MAX = 1e4 + 5;

struct node {
  int num;
  int clicks;
};

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n, m;
    cin>>n>>m;

    map<int, bool> visited;
    queue<node> Q;
    Q.push(node{m, 0});
    visited[m] = 1;

    while(!Q.empty()) {
      node cur = Q.front();
      Q.pop();

      if(cur.num == n) {
        cout<<cur.clicks<<endl;
        break;
      }

      visited[cur.num] = 1;

      if(cur.num % 2 == 0 && !visited[cur.num / 2])
        Q.push(node{cur.num / 2, cur.clicks + 1});
      
      if(cur.num < MAX && !visited[cur.num + 1])
        Q.push(node{cur.num + 1, cur.clicks + 1}); 
    }

    return 0;
}

