/**
*  Generated by tpp tool
*  File: 617A_Elephant.cpp
*  Created: 29-03-2024 01:48:10
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int x;
    cin>>x;

    int ans = (x/5) + (x % 5 > 0);
    cout<<ans<<endl;

    return 0;
}

