/**
*  Generated by tpp tool
*  File: 705A_Hulk.cpp
*  Created: 16-04-2024 17:41:54
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    string ans = "";
    for(int i = 0; i < n; i++) {
      if(i > 0) ans += " ";

      ans += "I";

      if(i % 2 == 0) ans += " hate";
      else ans += " love";

      if(i == n - 1) ans += " it";
      else ans += " that";
    }

    cout<<ans<<endl;

    return 0;
}

