/**
*  Generated by tpp tool
*  File: 734A_Anton_And_Danik.cpp
*  Created: 29-03-2024 01:58:15
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    string s;

    cin>>n;
    cin>>s;

    int anton = 0;
    int danik = 0;
    for(int i = 0; i < s.size(); i++) {
      if(s[i] == 'A') anton++;
      else danik++;
    }

    if(anton == danik) cout<<"Friendship"<<endl;
    else {
      if(anton > danik) cout<<"Anton"<<endl;
      else cout<<"Danik"<<endl;
    }
    return 0;
}

