/**
*  Generated by tpp tool
*  File: C.cpp
*  Created: 28-12-2023 11:49:08
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


bool isSquare(long long int n) {
  long long int square = sqrt(n);
  return (square * square == n);
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int t;
    cin>>t;

    while(t--) {
      int n;
      cin>>n;

      long long int sum = 0;
      for(int i = 0; i < n; i++) {
        long long int num;
        cin>>num;

        sum += num;
      }

      if(isSquare(sum)) cout<<"YES"<<endl;
      else cout<<"NO"<<endl;
    }

    return 0;
}

