/**
*  Generated by tpp tool
*  File: baloni.cpp
*  Created: 03-10-2020 12:35:36
**/

#include <bits/stdc++.h>
#define MAX 1000005
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    cin>>N;

    vector<int> cont(MAX, 0);
    for(int i = 0; i < N; i++) {
    	int H;
    	cin>>H;

    	if(cont[H] == 0) cont[H - 1]++;
    	else {
    		cont[H - 1]++;
    		cont[H]--;
    	}
    }


    int ans = 0;
    for(int i = 0; i < MAX; i++) ans += cont[i];
    cout<<ans<<endl;

    return 0;
}
