/**
*  Generated by tpp tool
*  File: associative_array.cpp
*  Created: 14-02-2024 22:53:47
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int Q;
    cin>>Q;

    unordered_map<long long int, long long int> M;

    for(int i = 0; i < Q; i++) {
      long long int k, v;
      int op;
      cin>>op;

      if(op) {
        cin>>k;
        cout<<M[k]<<endl;
      } else {
        cin>>k>>v;
        M[k] = v;
      }
    }

    return 0;
}

