/**
*  Generated by tpp tool
*  File: jollyjumpers.cpp
*  Created: 01-10-2021 10:41:38
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;

    while(cin>>n) {
        vector<int> numbers(n);
        map<int, bool> visited;
        int cont = 0;

        for(int i = 0; i < n; i++) {
            cin>>numbers[i];
            if(i > 0) {
                int value = abs(numbers[i] - numbers[i - 1]);
                if(value > 0 && value < n) {
                    if(!visited[value]) cont++;
                    visited[value] = true;
                }
                
            }
        }

        if(cont == n - 1) cout<<"Jolly"<<endl;
        else cout<<"Not jolly"<<endl;
    }

    return 0;
}

