/**
*  Generated by tpp tool
*  File: 11953_Battleships.cpp
*  Created: 01-01-2024 19:34:52
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define MOV 4
#define SHIP 'x'
#define SHOT '@'

int dr[] = {0, 1, 0, -1};
int dc[] = {1, 0, -1, 0};

int T, N;
int cases;
vector<string> graph;
vector<vector<bool>> visited;

bool isValid(int r, int c) {
  return r >= 0 && r < N && c >= 0 && c < N;
}

void dfs(int r, int c) {
  if(visited[r][c]) return;

  visited[r][c] = 1;

  for(int k = 0; k < MOV; k++) {
    int nr = r + dr[k];
    int nc = c + dc[k];

    if(isValid(nr, nc) && (graph[nr][nc] == SHIP || graph[nr][nc] == SHOT)) {
      dfs(nr, nc);
    }
  }
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    cases = 1;

    cin>>T;

    while(T--) {
      cin>>N;

      graph = vector<string>(N);
      visited = vector<vector<bool>>(N, vector<bool>(N, 0));

      for(int i = 0; i < N; i++) cin>>graph[i];

      int ans = 0;

      for(int i = 0; i < N; i++) {
        for(int j = 0; j < N; j++) {
          if(graph[i][j] == SHIP && !visited[i][j]) {
            dfs(i, j);
            ans++;
          }
        }
      }

      cout<<"Case "<<cases++<<": "<<ans<<endl;
    }

    return 0;
}

