/**
*  Generated by tpp tool
*  File: 572_Oil_Deposits.cpp
*  Created: 01-01-2024 17:16:21
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define OIL '@'
#define MOV 8

int dr[] = {0, 1, 1, 1, 0, -1,-1,-1};
int dc[] = {1, 1, 0, -1,-1,-1, 0, 1};

int R, C;
vector<string> graph;
vector<vector<bool>> visited;

bool isValid(int r, int c) {
  return r >= 0 && r < R && c >= 0 && c < C;
}

void dfs(int r, int c) {
  if(visited[r][c]) return;

  visited[r][c] = 1;

  for(int k = 0; k < MOV; k++) {
    int nr = r + dr[k];
    int nc = c + dc[k];

    if(isValid(nr, nc) && graph[nr][nc] == OIL) {
      dfs(nr, nc);
    }
  }
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    while(cin>>R>>C) {
      if(R == 0 && C == 0) break;

      graph = vector<string>(R);
      visited = vector<vector<bool>>(R, vector<bool>(C, 0));

      for(int i = 0; i < R; i++) cin>>graph[i];

      int ans = 0;
      for(int i = 0; i < R; i++) {
        for(int j = 0; j < C; j++) {
          if(graph[i][j] == OIL && !visited[i][j]) {
            dfs(i, j);
            ans++;
          }
        }
      }

      cout<<ans<<endl;
    }

    return 0;
}

