/**
*  Generated by tpp tool
*  File: 1621_Distinct_Numbers.cpp
*  Created: 13-02-2024 22:55:57
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n;
    cin>>n;

    vector<int> V(n);
    for(int i = 0; i < n; i++) cin>>V[i];

    sort(V.begin(), V.end());

    int last = 0;
    int ans = 0;
    for(int i = 0; i < n; i++) {
      if(V[i] != last) {
        ans++;
        last = V[i];
      }
    }

    cout<<ans<<endl;

    return 0;
}

