/**
*  Generated by tpp tool
*  File: Dont_Be_Last.cpp
*  Created: 20-02-2024 19:40:27
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define COW_NUM 7

bool order(pair<string, int> p1, pair<string, int> p2) {
  return p1.second < p2.second;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    freopen("notlast.in", "r", stdin);
    freopen("notlast.out", "w", stdout);

    int N;
    cin>>N;

    map<string, int> M;
    while(N--) {
      string name;
      int amount;
      cin>>name>>amount;

      M[name] += amount;
    }

    vector<pair<string,int>> V(M.begin(), M.end());
    sort(V.begin(), V.end(), order);

    int pos = 0;
    int first = V[pos].second;

    if(V.size() == COW_NUM) {
      while(pos < V.size() && V[pos].second == first) pos++;
    }

    if(pos < V.size() && (pos + 1 ==  V.size()) || V[pos].second != V[pos + 1].second)
      cout<<V[pos].first<<endl;
    else
      cout<<"Tie"<<endl;

    return 0;
}

