/**
*  Generated by tpp tool
*  File: Where_Am_I.cpp
*  Created: 15-02-2024 01:13:56
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    freopen("whereami.in", "r", stdin);
    freopen("whereami.out", "w", stdout);

    int N;
    cin>>N;

    string s;
    cin>>s;

    unordered_map<string,int> M;
    vector<int> V(N + 1);

    for(int i = 0; i < s.size(); i++) {
      string aux = "";
      for(int j = i; j < s.size(); j++) {
        aux += s[j];
        M[aux]++;

        int size = aux.size();
        V[size] = max(V[size], M[aux]);
      }
    }

    int ans = 0;
    for(int i = 1; i < V.size(); i++) {
      if(V[i] == 1) {
        ans = i;
        break;
      }
    }

    cout<<ans<<endl;

    return 0;
}

