/**
*  Generated by tpp tool
*  File: abc339_a.cpp
*  Created: 03-02-2024 09:06:26
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    string S;
    cin>>S;

    int ind = S.size() - 1;
    string ans = "";

    while(ind >= 0 && S[ind] != '.') {
      ans += S[ind--];
    }

    reverse(ans.begin(), ans.end());
    cout<<ans<<endl;

    return 0;
}

