/**
*  Generated by tpp tool
*  File: abc347_b_Substring.cpp
*  Created: 30-03-2024 09:27:14
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    string s;
    cin>>s;

    set<string> str;

    for(int len = 1; len <= s.size(); len++) {
      for(int i = 0; i < s.size(); i++) {
        if(i + len <= s.size()) {
          string aux = s.substr(i, len);
          str.insert(aux);
        }
      }
    }

    cout<<str.size()<<endl;

    return 0;
}

