/**
*  Generated by tpp tool
*  File: abc340_b.cpp
*  Created: 10-02-2024 17:51:12
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int Q;
    cin>>Q;

    vector<int> V;
    while(Q--) {
      int op;
      cin>>op;

      if(op == 1) {
        int num;
        cin>>num;

        V.push_back(num);
      } else {
        int pos;
        cin>>pos;

        cout<<V[V.size() - pos]<<endl;
      }
    }

    return 0;
}

