/**
*  Generated by tpp tool
*  File: abc340_a_Arithmetic_Progression.cpp
*  Created: 10-02-2024 17:47:20
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int A, B, D;
    cin>>A>>B>>D;

    for(int i = A; i <= B; i += D) {
      if(i != A) cout<<" ";
      cout<<i;
    }
    cout<<endl;

    return 0;
}

