/**
*  Generated by tpp tool
*  File: abc343_a_Wrong_Answer.cpp
*  Created: 03-03-2024 16:55:38
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int A, B;
    cin>>A>>B;

    map<int, int> M;
    M[A]++;
    M[B]++;

    int ans = 0;

    for(int i = 0; i < 10; i++) {
      if(!M.count(i)) {
        ans = i;
        break;
      }
    }

    cout<<ans<<endl;

    return 0;
}

