/**
*  Generated by tpp tool
*  File: abc343_b_Adjacency_Matrix.cpp
*  Created: 03-03-2024 17:09:24
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    cin>>N;

    bool M[N][N];

    for(int i = 0; i < N; i++) {
      for(int j = 0; j < N; j++) cin>>M[i][j];
    }

    for(int i = 0; i < N; i++) {
      int cont = 0;
      for(int j = 0; j < N; j++) {
        if(M[i][j]) {
          if(cont != 0) cout<<" ";

          cont++;
          cout<<j+1;
        }
      }
      cout<<endl;
    }

    return 0;
}

