/**
*  Generated by tpp tool
*  File: abc344_b_Delimiter.cpp
*  Created: 09-03-2024 09:08:59
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    stack<int> S;
    int num;

    while(cin>>num) S.push(num);

    while(!S.empty()) {
      cout<<S.top()<<endl;
      S.pop();
    }

    return 0;
}

