/**
*  Generated by tpp tool
*  File: abc339_c.cpp
*  Created: 03-02-2024 09:42:50
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    cin>>N;

    long long int sum = 0;
    for(int i = 0; i < N; i++) {
      long long int num;
      cin>>num;

      sum += num;
      if(sum < 0) sum = 0;
    }

    cout<<sum<<endl;

    return 0;
}

