/**
*  Generated by tpp tool
*  File: abc344_c_ABC.cpp
*  Created: 09-03-2024 09:15:47
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N, M, L, Q;

    cin>>N;
    vector<int> A(N);
    for(int i = 0; i < N; i++) cin>>A[i];

    cin>>M;
    vector<int> B(M);
    for(int i = 0; i < M; i++) cin>>B[i];

    cin>>L;
    vector<int> C(L);
    for(int i = 0; i < L; i++) cin>>C[i];

    map<int, bool> see;

    for(int i = 0; i < N; i++) {
      for(int j = 0; j < M; j++) {
        for(int k = 0; k < L; k++) {
          int sum = A[i] + B[j] + C[k];
          see[sum] = 1;
        }
      }
    }

    cin>>Q;
    for(int i = 0; i < Q; i++) {
      int X;
      cin>>X;

      if(see.count(X)) cout<<"Yes"<<endl;
      else cout<<"No"<<endl;
    }

    return 0;
}

