/**
*  Generated by tpp tool
*  File: abc340_c_Divide_And_Divide.cpp
*  Created: 10-02-2024 18:02:01
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


map<long long int, long long int> dp;

long long int solve(long long int n) {
  if(n == 1) return 0;
  if(dp[n]) return dp[n];

  long long int f = n/2;
  long long int c = (n + 1)/2; 
  return dp[n] = n + solve(f) + solve(c); 
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    long long int N;
    cin>>N;

    cout<<solve(N)<<endl;
    return 0;
}

