/**
*  Generated by tpp tool
*  File: 10038_Jolly_Jumpers.cpp
*  Created: 11-01-2024 11:53:25
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    while(cin>>N) {

      vector<bool> visited(N, 0);
      vector<int> V(N);

      for(int i = 0; i < N; i++) {
        cin>>V[i];

        if(i > 0) {
          int diff = abs(V[i] - V[i - 1]);
          if(diff < N) visited[diff] = 1;
        } 
      }

      bool isJolly = 1;
      
      for(int i = 1; i < N; i++) {
        if(!visited[i]) {
          isJolly = 0;
          break;
        }
      }

      if(isJolly) cout<<"Jolly"<<endl;
      else cout<<"Not jolly"<<endl;
    }

    return 0;
}

