/**
*  Generated by tpp tool
*  File: 10107_What_Is_The_Median.cpp
*  Created: 11-01-2024 13:59:45
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    long long int num;
    vector<long long int> V;

    while(cin>>num) {
      V.push_back(num);
      sort(V.begin(), V.end());

      int mid = V.size()/2;
      
      if(V.size() % 2 != 0) cout<<V[mid]<<endl;
      else cout<<(V[mid - 1] + V[mid])/2<<endl;
    }

    return 0;
}

