/**
*  Generated by tpp tool
*  File: 11462_Age_Sort.cpp
*  Created: 11-01-2024 14:13:07
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define MAX 100

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N, num;
    while(cin>>N) {
      if(N == 0) break;

      vector<int> V;
      for(int i = 0; i < N; i++) {
        cin>>num;

        if(num <= MAX) V.push_back(num);
      }

      sort(V.begin(), V.end());

      for(int i = 0; i < V.size(); i++) {
        if(i != 0) cout<<" ";
        cout<<V[i];
      }
      cout<<endl;
    }

    return 0;
}

