/**
*  Generated by tpp tool
*  File: Cow_College.cpp
*  Created: 14-02-2024 09:23:45
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int N;
    cin>>N;

    vector<long long int> V(N);
    for(int i = 0; i < N; i++) cin>>V[i];

    sort(V.begin(), V.end());
    
    long long int amount = 0;
    long long int tuition = 0;
    for(int i = 0; i < N; i++) {
      long long int candidate = V[i]*(N - i);
      if(candidate > amount) {
        amount = candidate;
        tuition = V[i];
      }
    }
    
    cout<<amount<<" "<<tuition<<endl;
    return 0;
}

