/**
*  Generated by tpp tool
*  File: Why_Did_The_Cow_Cross_The_Road_III.cpp
*  Created: 14-02-2024 01:11:45
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


struct cow {
  int time;
  int duration;
};

bool order(cow &c1, cow &c2) {
  return c1.time < c2.time;
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    freopen("cowqueue.in", "r", stdin);
    freopen("cowqueue.out", "w", stdout);

    int N;
    cin>>N;

    vector<cow> V;

    for(int i = 0; i < N; i++) {
      int time, duration;
      cin>>time>>duration;

      V.push_back(cow{time, duration});
    }

    sort(V.begin(), V.end(), order);

    int threshold = 0;
    for(int i = 0; i < N; i++) {
      if(V[i].time > threshold) threshold = V[i].time + V[i].duration;
      else threshold = threshold + V[i].duration;
    }

    cout<<threshold<<endl;

    return 0;
}

