/**
*  Generated by tpp tool
*  File: dp_f_back.cpp
*  Created: 27-02-2024 02:16:14
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


string S, T;
int N, M;

int solve(int i, int j) {
  if(i >= N || j >= M) return 0;

  int len1 = 0, len2 = 0, len3 = 0;

  if(S[i] == T[j]) len1 = max(len1, 1 + solve(i + 1, j + 1));
  len2 = solve(i + 1, j);
  len3 = solve(i, j + 1);

  return max(len1, max(len2, len3));
}

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    cin>>S;
    cin>>T;

    N = S.size();
    M = T.size();

    int len = solve(0, 0);

    cout<<len<<endl;

    return 0;
}

