/**
*  Generated by tpp tool
*  File: Mixing_Milk.cpp
*  Created: 06-02-2024 15:26:53
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


#define SIZE 3
#define POURS 100

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    freopen("mixmilk.in", "r", stdin);
    freopen("mixmilk.out", "w", stdout);
    
    vector<int> capacity(SIZE), milk(SIZE);

    for(int i = 0; i < SIZE; i++) cin>>capacity[i]>>milk[i];

    for(int i = 0; i < POURS; i++) {
      int current = i % SIZE;
      int next = (i + 1) % SIZE;

      int accumulated = milk[current] + milk[next];
      milk[current] = max(0, accumulated - capacity[next]);
      milk[next] = min(accumulated, capacity[next]);
    }

    for(int i = 0; i < SIZE; i++) cout<<milk[i]<<endl;

    return 0;
}

