/**
*  Generated by tpp tool
*  File: Shell_Game.cpp
*  Created: 06-02-2024 14:31:19
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;

#define SIZE 3

int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    freopen("shell.in", "r", stdin);
    freopen("shell.out", "w", stdout);

    int N;
    cin>>N;

    vector<int> position(SIZE), count(SIZE);
    for(int i = 0 ; i < SIZE; i++) position[i] = i;

    for(int i = 0; i < N; i++) {
      int a, b, g;
      cin>>a>>b>>g;

      a--;
      b--; 
      g--;

      swap(position[a], position[b]);
      count[position[g]]++;
    }

    int ans = max(count[0], max(count[1], count[2]));
    cout<<ans<<endl;

    return 0;
}

