/**
*  Generated by tpp tool
*  File: 1640_Sum_Of_Two_Values.cpp
*  Created: 15-02-2024 00:30:56
**/

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <bitset>
#include <sstream>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <cstring>
using namespace std;


int main() {
    // do not remove this code if you use cin or cout
    ios::sync_with_stdio(false);
    cin.tie(0);

    int n, x;
    cin>>n>>x;

    map<int, int> M;
    vector<int> V(n);
    for(int i = 0; i < n; i++) {
      cin>>V[i];
      M[V[i]] = i;
    }

    int j, k;
    bool found = 0;
    for(j = 0; j < n; j++) {
      int diff = x - V[j];
      if(M.count(diff) && M[diff] != j) {
        k = M[diff];
        found = 1;
        break;
      }
    }

    if(!found) cout<<"IMPOSSIBLE"<<endl;
    else cout<<j + 1<<" "<<k + 1<<endl;

    return 0;
}

